# OBSOLETE replaced by jedisct1/phusion-baseimage-latest:16.04 for smaller image size
# Use passenger-docker https://github.com/phusion/passenger-docker#using-the-image-as-base
FROM phusion/passenger-full:0.9.19

# Set correct environment variables.
ENV HOME /root

# Use baseimage-docker's init process.
CMD ["/sbin/my_init"]

# Enable the Redis service.
RUN rm -f /etc/service/redis/down

# >>> START CUSTOM BUILD
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y \
    python-pip \
    libjpeg8-dev \
    libfreetype6-dev \
    libz-dev \
    libjpeg-dev \
    gettext

RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install -y nodejs
RUN npm install -g phantomjs-prebuilt@2.1.14
RUN npm install -g casperjs@1.1.3
RUN npm install -g bower@1.8.0

WORKDIR /home/app
ADD requirements.txt /home/app/
RUN pip install -r requirements.txt
ADD . /home/app/
# <<< END CUSTOM BUILD

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
